import type { Config } from "tailwindcss";

const config: Config = {
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
        heading: ["var(--font-heading)", "serif"],
      },
      colors: {
        primary: "#0b6e8b",
        "on-primary": "#ffffff",
        "primary-container": "#1389aa",
        "on-primary-container": "#f0faff",
        secondary: "#4a6470",
        "on-secondary": "#ffffff",
        "secondary-container": "#cbe4ec",
        "on-secondary-container": "#506870",
        background: "#f7f9fc",
        "on-background": "#0e1b26",
        surface: "#f7f9fc",
        "on-surface": "#0e1b26",
        "on-surface-variant": "#3a4a55",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eef3fa",
        "surface-container": "#e4edf7",
        "surface-container-high": "#d8e6f2",
        "surface-container-highest": "#cce0ee",
        "surface-dim": "#cdd8e8",
        "inverse-surface": "#1e2d3a",
        "inverse-on-surface": "#e8f2ff",
        outline: "#6a7d8a",
        "outline-variant": "#b8c9d4",
        error: "#c0281f",
        "on-error": "#ffffff",
        "error-container": "#ffe4e1",
        "on-error-container": "#7b0a00",
        "surface-variant": "#d2e4ef",
        "surface-tint": "#0b6e8b",
        "inverse-primary": "#62cfec",
        accent: "#fff0dc",
        "accent-foreground": "#7a3c00",
        success: "#1a7a4a",
        "success-container": "#c8f2dc",
        "on-success": "#ffffff",
        "on-success-container": "#003d20",
        "primary-fixed": "#b3e8f8",
        "primary-fixed-dim": "#62cfec",
        "on-primary-fixed": "#001b24",
        "on-primary-fixed-variant": "#004f66",
        "secondary-fixed": "#cbe4ec",
        "secondary-fixed-dim": "#aecdd6",
        "on-secondary-fixed": "#0a1e24",
        "on-secondary-fixed-variant": "#2e4a52",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1.25rem",
        xl: "2rem",
        full: "9999px",
      },
      fontSize: {
        "display-xl": ["64px", { lineHeight: "1.15", fontWeight: "400", letterSpacing: "-0.025em" }],
        "display-xl-mobile": ["44px", { lineHeight: "1.2", fontWeight: "400", letterSpacing: "-0.01em" }],
        "display-lg": ["52px", { lineHeight: "1.2", fontWeight: "400", letterSpacing: "-0.02em" }],
        "headline-lg": ["40px", { lineHeight: "1.3", fontWeight: "400", letterSpacing: "-0.01em" }],
        "headline-lg-mobile": ["44px", { lineHeight: "1.2", fontWeight: "400", letterSpacing: "-0.01em" }],
        "headline-md": ["28px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-lg": ["19px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-md": ["17px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-lg": ["17px", { lineHeight: "1.4", fontWeight: "600", letterSpacing: "0.01em" }],
        "label-md": ["15px", { lineHeight: "1.4", fontWeight: "600", letterSpacing: "0.02em" }],
        "label-sm": ["13px", { lineHeight: "1.2", fontWeight: "700", letterSpacing: "0.04em" }],
      },
    },
  },
};

export default config;